import os
import requests

from ai.groq_engine import GroqAI


class TelegramNotifier:
    """
    Sends trading signals to Telegram channel
    """

    def __init__(self):
        self.token = os.getenv("TELEGRAM_BOT_TOKEN")
        self.channel = os.getenv("CHANNEL_ID")
        self.ai = GroqAI()

    # =========================
    # 📡 SEND MESSAGE
    # =========================
    def send(self, text: str):
        url = f"https://api.telegram.org/bot{self.token}/sendMessage"

        payload = {
            "chat_id": self.channel,
            "text": text,
            "parse_mode": "HTML"
        }

        requests.post(url, data=payload)

    # =========================
    # 🧠 FORMAT SIGNAL
    # =========================
    def format_signal(self, signal: dict, price: float):
        return f"""
🚀 <b>CryptoPulse SIGNAL</b>

📊 Signal: <b>{signal['signal']}</b>
💰 Price: {price}
📈 Score: {signal.get('score', 'N/A')}

⚠️ Auto-generated by AI System
"""

    # =========================
    # 🧠 AI EXPLANATION
    # =========================
    def explain(self, signal: dict):
        prompt = f"""
        Explain this trading signal:
        Signal: {signal}
        Make it short and professional.
        """

        return self.ai.ask(prompt)

    # =========================
    # 🚀 MAIN PUSH FUNCTION
    # =========================
    def push_signal(self, signal: dict, price: float):
        text = self.format_signal(signal, price)
        explanation = self.explain(signal)

        final_message = f"""
{text}

🧠 <b>AI Analysis:</b>
{explanation}
"""

        self.send(final_message)
